"""Initial schema for the crawler metadata registry.

The first migration materialises the full model metadata via
``Base.metadata.create_all``. This guarantees the initial schema is a faithful
mirror of the ORM models; subsequent migrations are hand-written / autogenerated
deltas.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-08
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

from crawler.models.registry import Base

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all crawler tables."""
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    """Drop all crawler tables."""
    Base.metadata.drop_all(bind=op.get_bind())
